### ISSUE TITLE
Dependencies inconsistent with scala-output-version

### ISSUE THREAD

**Issue by armanbilge** [monix/newtypes#23]
Unfortunately setting the `-scala-output-version` flag is not sufficient. Currently newtypes is published with a dependency on the Scala 3.1.2 standard lib, which makes it difficult to use from a Scala 3.0 project :)
https://repo1.maven.org/maven2/io/monix/newtypes-core_3/0.2.2/newtypes-core_3-0.2.2.pom

Configuring this is complex enough that sbt will be getting special support for it in 1.7.0:
https://github.com/sbt/sbt/releases/tag/v1.7.0-M2

**Comment by alexandru** [comment]
Yikes. I should probably just downgrade to 3.0.2.

**Comment by alexandru** [comment]
Maybe you're right. 

I noticed 3.1.2 having type inference issues, not happening in 3.1.0, which is why I've had [to fill some obvious type params](https://github.com/monix/newtypes/blob/v0.2.2/core/shared/src/test/scala/monix/newtypes/NewtypeKSuite.scala#L94); possibly a bug I need to minimize and report, which made me want to downgrade to 3.0 for the output.

**Comment by alexandru** [comment]
I published `0.2.3`.

https://github.com/monix/newtypes/releases/tag/v0.2.3
